## Exceptions (#2)

Write a function called `abort()` that takes a `String` parameter, then throws a
plain `Exception` object, passing the `abort()` argument to the `Exception`
constructor. In `main()`, call `abort()` with an argument of `"Stop!"` and use
`capture` to verify the result.
